### ISSUE TITLE
Team rating

### ISSUE THREAD

**Issue by BassExtractor** [ertkjern/fuss-rating#9]
Be able to play a 2v2 match, where the players on the winning team gets rating.
Suggestion for calculations:
The rating of the team is the average of the individual players on the team:
Team 1: 1500 + 1700 = 1600
Team 2: 1600 + 1550 = 1575

These team average ratings can use ELO calculations.

**Comment by ertkjern** [comment]
Good suggestion, will implement as soon as possible

**Comment by palexcast** [comment]
Working on it 👍 hopefully done sometime this week

**Comment by ertkjern** [comment]
Related PR: https://github.com/ertkjern/fuss-rating/pull/28

**Comment by ertkjern** [comment]
Solved, will be released in one of the upcoming days
